// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify.
// It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-east-1',
    aws_cognito_identity_pool_id: 'us-east-1:01846c08-8ddb-48d6-b443-a9e0a66b5601',
    aws_cognito_region: 'us-east-1',
    aws_user_pools_id: 'us-east-1_LWG5fRyCt',
    aws_user_pools_web_client_id: '10akt6ulmvs21vtqrq7i42fpdp',
    oauth: {},
  };
  
  
  export default awsmobile;